- hosts: kubadmin
  become: yes
  tasks: 
  - name: git 
    git:
      repo: https://github.com/TejasPatel21/k8s-dashboard.git
      dest: /home/kubadmiins/
  - name: create new deployment
    shell: kubectl apply -f /home/kubadmiins/k8smvndeployment.yaml
  - name: create prometheus monitoring
    shell: ./deploy 